= SFTP File Transfer In Java Using Jsch Library

Khairul Islam Azam <Khairulislam.azam@gmail.com>

== What is SFTP file transfer?

----
Secure File Transfer Protocol (SFTP) is a secure version of File Transfer Protocol (FTP) and a part of the SSH Protocol for easy data transfer and data access over a Secure Shell (SSH) data stream. SFTP is also known as SSH File Transfer Protocol.
----

== `Features`


== *Connection method*


_This method is used for creating sftpchannel so that user can upload or download or deleting file. First we need jsch class after that creating session from jsch object giving the username, host, port, after that a Channel connected to an sftp server (as a subsystem of the ssh server)._

* *@return* : after connecting the channel it shloud return the connect sftpchannel.

----
     private ChannelSftp createChannelSftp() {
        try {
            JSch jSch = new JSch();
            jSch.addIdentity(privatekey, passphrase.getBytes());
            Session session = jSch.getSession(username, host, port);
            session.setConfig("StrictHostKeyChecking", "no");
            session.connect(sessionTimeout);
            Channel channel = session.openChannel("sftp");
            channel.connect(channelTimeout);
            return (ChannelSftp) channel;
        } catch (JSchException ex) {
            logger.error("Create ChannelSftp error", ex);
        }

        return null;
    }
----

== *File Upload method*


_This method is used for file upload file from client to server._

* *@param localFilePath* :  Here localFilePath is the local directory used for client
who upload file from his pc or any other device
* *@param remoteFilePath* : Here remoteFilepath is the directory of your server where you can store your file
* *@return* : after storing your file this method, return boolean value to ensure that your file is saved or not.

----
    public boolean uploadFile(MultipartFile file, String remoteFilePath) {
        ChannelSftp channelSftp = createChannelSftp();

        if (remoteDirectoryCk(remoteFilePath)) {
            try {
                File convFile = convertMultiPartToFile(file);
                if (convFile.canRead()) {
                    channelSftp.put(new FileInputStream(convFile),
                            remoteFilePath + "/" + convFile.getName());
                    return true;
                }

            } catch (SftpException | FileNotFoundException ex) {
                logger.error("Error upload file", ex);
            } catch (IOException e) {
                logger.error("Error upload file", e);
            } finally {
                disconnectChannelSftp(channelSftp);
            }
        }
        return false;
    }
----
